name: Feature Request
description: Suggest an idea or enhancement for exhaustruct analyzer
title: "[Feature]: "
labels: ["enhancement"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a new feature! Please provide as much detail as possible to help us understand your request.

  - type: textarea
    id: problem-summary
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of what the problem is
      placeholder: I'm always frustrated when... / It would be helpful if... / Currently exhaustruct doesn't support...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen
      placeholder: I would like exhaustruct to...
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe your specific use case and how this feature would help
      placeholder: |
        In my project, I often need to...
        This feature would help by...
        Current workaround (if any)...
    validations:
      required: true
